In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [2]:
list_

['1', '2', '3', '4', '5']

In [3]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [4]:
type(list_)

list

In [5]:
type(array_list)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [6]:
list_

['1', '2', '3', '4', '5']

In [8]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [9]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [11]:
for j in array_list:
    print(type(j))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_
and array_list.

In [12]:
array_list = np.array(object = list_, dtype = int)

In [13]:
array_list

array([1, 2, 3, 4, 5])

In [14]:
type(list_)

list

In [17]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [18]:
type(array_list)

numpy.ndarray

In [19]:
for j in array_list:
    print(type(j))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [1]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [2]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
np.shape(num_array)

(2, 3)

In [4]:
np.size(num_array)

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [5]:
arr = np.zeros((3,3))

In [6]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [8]:
identity_matrix = np.eye(5)

In [9]:
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])